package-lock.json
packages/telestion-client-template/package.json
packages/telestion-client-template/template/.gitignore.ejs
packages/telestion-client-template/template/package.json.ejs

- add CLI locally in template with npm scripts

fix(template): Fix multiple template issues

---

lerna.json
packages/telestion-client-common/src/components/index.ts
packages/telestion-client-common/src/components/widget-helper/index.ts
packages/telestion-client-common/src/components/widget-helper/loading-indicator.tsx
packages/telestion-client-common/src/hooks/index.ts
packages/telestion-client-common/src/hooks/use-dependency-timeout.ts

feat(common): Add dependency timeouts hook and Loading Indicator component

---

.github/workflows/release.yml
lerna.json

chore(ci): Add node_modules binaries to path in Release Workflow

---

lerna.json
packages/telestion-client-common/src/components/pages/login-page/login-description.tsx
packages/telestion-client-common/src/components/pages/login-page/login-form/login-form.tsx
packages/telestion-client-common/src/components/pages/login-page/login-logo.tsx
packages/telestion-client-common/src/components/pages/login-page/login-page.tsx
packages/telestion-client-common/src/components/pages/login-page/login-title.tsx
packages/telestion-client-template/template/src/components/login-page.tsx.ejs

fix: Fix custom login page implementation in both the template and documentation

---

packages/telestion-client-cli/src/commands/docs.js
packages/telestion-client-cli/src/commands/start.js
packages/telestion-client-cli/src/lib/open-url.js
packages/telestion-client-template/template/package.json.ejs

Please merge by rebasing all commits onto master, the commit structure of the branch matches the necessary changelog entries.

feat(cli): Opening the PSC in the browser

---

.github/workflows/test.yml
packages/telestion-client-cli/src/commands/build.js
packages/telestion-client-cli/src/commands/docs.js
packages/telestion-client-cli/src/commands/generate.js
packages/telestion-client-cli/src/commands/init.js
packages/telestion-client-cli/src/commands/start.js
packages/telestion-client-cli/src/commands/stats.js
packages/telestion-client-cli/src/lib/init/ask-project-name.js
packages/telestion-client-cli/src/lib/init/git-init.js
packages/telestion-client-cli/src/lib/init/npm-install.js
packages/telestion-client-cli/src/lib/init/package-json-replacers.js
packages/telestion-client-cli/src/lib/init/template-parser.js
packages/telestion-client-cli/src/lib/logger.js
packages/telestion-client-cli/src/lib/promise-minimum-time.js

Multiple fixes in the telestion-client-cli.
Commits lead to the expected Changelog => Please merge via rebase.

MERGE-VIA-REBASE fix(cli)

---

packages/telestion-client-common/src/components/pages/login-page/login-description.tsx

REBASE: fix(common): Type Error in login description component

---

.github/workflows/test.yml
package-lock.json
packages/telestion-client-cli/package.json
packages/telestion-client-cli/src/commands/build.js
packages/telestion-client-cli/src/commands/docs.js
packages/telestion-client-cli/src/commands/init.js
packages/telestion-client-cli/src/commands/start.js
packages/telestion-client-cli/src/lib/build/compile-electron-main-thread.js
packages/telestion-client-cli/src/lib/build/compile-react-app.js
packages/telestion-client-cli/src/lib/build/custom-webpack-loader/electron-main-import-plugins.js
packages/telestion-client-cli/src/lib/build/package-electron-app.js
packages/telestion-client-cli/src/lib/build/static/electron-main.js
packages/telestion-client-cli/src/lib/build/with-adjusted-package-json-run.js
packages/telestion-client-cli/src/lib/config.js
packages/telestion-client-cli/src/lib/generate/widget/index.js
packages/telestion-client-cli/src/lib/init/git-init.js
packages/telestion-client-cli/src/lib/init/normalize-module-name.js
packages/telestion-client-cli/src/lib/init/process-template-tree.js
packages/telestion-client-cli/src/lib/logger.js
packages/telestion-client-cli/src/lib/modify-file.js
packages/telestion-client-cli/src/lib/open-url.js
packages/telestion-client-template/package.json
packages/telestion-client-template/template/package.json.ejs
packages/telestion-client-template/template/telestion.config.js.ejs

MERGE-BY-REBASE: feat(cli): `tc-cli build` command

---

CONTRIBUTING.md
README.md

docs: README improvements

---

package-lock.json
packages/telestion-client-cli/package.json
packages/telestion-client-cli/src/api.js
packages/telestion-client-cli/src/commands/build.js
packages/telestion-client-cli/src/commands/start.js
packages/telestion-client-cli/src/lib/build/compile-electron-main-thread.js
packages/telestion-client-cli/src/lib/get-config.js
packages/telestion-client-cli/src/lib/prepare-environment.js
packages/telestion-client-cli/src/lib/run-in-psc-project-dir.js

Run actual Electron app and use Craco script for `tc-cli start -e`

MERGE-BY-REBASE: feat/cli/start-improvements

---

README.md
package-lock.json
packages/telestion-client-cli/README.md
packages/telestion-client-common/README.md
packages/telestion-client-core/README.md
packages/telestion-client-prop-types/README.md
packages/telestion-client-template/README.md
packages/telestion-client-template/package.json
packages/telestion-client-template/template/README.md.ejs
packages/telestion-client-types/README.md
packages/vertx-event-bus/README.md
packages/vertx-mock-server/README.md

Updating package and template READMEs

MERGE-BY-REBASE: docs/package-readme-updates

---

packages/vertx-mock-server/src/vertx-mock-server.ts

REBASE: feat(mock-server): Make prefix and hostname customizable

---

package-lock.json
packages/telestion-client-common/src/components/header/app-logo.tsx
packages/telestion-client-common/src/components/header/header.tsx
packages/telestion-client-common/src/components/header/nav-bar/nav-bar.tsx
packages/telestion-client-core/src/lib/logger.ts
packages/vertx-event-bus/src/logger.ts
packages/vertx-event-bus/src/vertx-event-bus.ts

Compatibility fixes for React Spectrum 3.8 and optimization of imports

MERGE-BY-REBASE: fix/react-spectrum-3.8-compat-fixes

---

packages/telestion-client-types/src/json-serializable.ts

REBASE: fix(types): Add possible types to JSON serializable in object and array

---

packages/telestion-client-types/src/widgets/widget.ts

REBASE: fix(types): Allow undefined in generic props for widgets

---

package-lock.json
package.json
packages/telestion-client-types/package.json
packages/telestion-client-types/src/vertx-event-bus/options.ts
packages/vertx-event-bus/src/basic-event-bus.ts
packages/vertx-event-bus/src/lib/filter-duplicates.ts
packages/vertx-event-bus/src/lib/index.ts
packages/vertx-event-bus/src/model/default-options.ts
packages/vertx-event-bus/src/vertx-event-bus.spec.ts
packages/vertx-event-bus/src/vertx-event-bus.ts

REBASE: fix(event-bus): Fix message and callback handling and add additional logging options

---

packages/telestion-client-common/src/components/header/dashboard-picker/use-dashboard-state.ts

Fix dashboard picker does not display the current dashboard title on initial load
The `Header` component is not a child of a react-router `Route` component, so the `useParams` hook does not update when `location` object changes.
For now, the component uses the "raw" `location.pathname` und extracts the dashboard route `id` there.
- Fixes #363

Fix dashboard picker

---

package-lock.json
packages/telestion-client-common/package.json
packages/telestion-client-common/src/index.ts
packages/telestion-client-common/src/widgets/eventbus-debug-widget/components/build-details.ts
packages/telestion-client-common/src/widgets/eventbus-debug-widget/components/details-table.tsx
packages/telestion-client-common/src/widgets/eventbus-debug-widget/components/eventbus-details.tsx
packages/telestion-client-common/src/widgets/eventbus-debug-widget/hooks/index.ts
packages/telestion-client-common/src/widgets/eventbus-debug-widget/hooks/use-auto-refresh.ts
packages/telestion-client-common/src/widgets/eventbus-debug-widget/hooks/use-error-message-state.ts
packages/telestion-client-common/src/widgets/eventbus-debug-widget/index.ts
packages/telestion-client-common/src/widgets/eventbus-debug-widget/widget.tsx
packages/telestion-client-common/src/widgets/index.ts
packages/telestion-client-template/package.json
packages/telestion-client-template/template/src/components/app.tsx.ejs

Implementation of the eventbus debug widget
- **common**: Add the eventbus debug widget. To use it, simply add the `commonWidgets` to the widgets list of the `CommonWrapper` component.
- **template**: Import common widgets into application by default
https://user-images.githubusercontent.com/52416718/120874130-a6d8f480-c594-11eb-9906-8e6218343c87.mp4
- Fixes #262

Eventbus Debug Widget

---

package-lock.json

Reverts wuespace/telestion-client#917

revert: chore(deps): bump @adobe/react-spectrum from 3.13.0 to 3.14.0"

---

packages/telestion-client-cli/src/lib/generate/widget/index.js
packages/telestion-client-template/template/src/widgets/index.ts.ejs

Closes: #1257
Yes, I’ve signed the CLA.

fix(telestion-client-cli): Fix type error in widget generation with generic types
